apiVersion : apps/v1
kind: Deployment
metadata:
  name: demoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
        - name: demoapi
          image: mainstxcr.azurecr.io/demoapi
          ports:
          - containerPort: 80